### ISSUE TITLE
Error Syncing. Error: Failed to get repo content, status 404

### ISSUE THREAD

**Issue by manuelscurti** [silvanocerza/github-gitless-sync#7]
Hey there!
First of all, thanks for your contribution. I see a lot of value in this plugin with its cross-platform compatibility.

I was trying to configure it to sync my Obsidian vault to a GitHub **private** repository, but when I trigger the sync process I get this error:
![Image](https://github.com/user-attachments/assets/22b66e70-0205-478d-a37d-9b31147f62ea)

Here is my config section on Obsidian:

![Image](https://github.com/user-attachments/assets/1f12a02a-2b3c-4a7b-86bf-c7c14509e686)

The token you see there is configured to read/write to that specific repository, so I imagine it's not auth error but instead I would expect something else is happening (given the HTTP response code). 

Here you have some logs during sync process:

```
{"timestamp":"2025-04-16T21:43:45.459Z","level":"INFO","message":"Starting sync"}
{"timestamp":"2025-04-16T21:43:45.819Z","level":"ERROR","message":"Failed to get repo content","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-encoding":"gzip","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Wed, 16 Apr 2025 21:43:45 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-accepted-github-permissions":"contents=read","x-content-type-options":"nosniff","x-github-api-version-selected":"2022-11-28","x-github-media-type":"github.v3; format=json","x-github-request-id":"D863:1AC6D4:1600646:16ACD61:68002491","x-ratelimit-limit":"5000","x-ratelimit-remaining":"4982","x-ratelimit-reset":"1744843115","x-ratelimit-resource":"core","x-ratelimit-used":"18","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/git/trees#get-a-tree","status":"404"},"text":"{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest/git/trees#get-a-tree\",\n  \"status\": \"404\"\n}\n"}}
```

Also, the `github-sync-metadata.json` is being created in my `.obsidian` settings folder

What am I missing? 
Thanks

**Comment by silvanocerza** [comment]
Thanks for the report. 

Strange though, this should work. I'll try to reproduce it later today. 🤔 

`github-sync-metadata.json` is created when the plugin is first enabled, so it's always going to be there, even if the sync failed.

**Comment by manuelscurti** [comment]
Was wondering, could it be related to the hyphen in the repository name?

**Comment by silvanocerza** [comment]
> Was wondering, could it be related to the hyphen in the repository name?

No, that doesn't cause any issues.

In any case I just tried to reproduce the issue by creating a new private repository and syncing my vault, it worked with no issues. Both latest stable and beta. 

Maybe you misclicked a key when pasting the token? Or a stray space? Now that I think about it I don't strip the token string of white spaces so it could very well cause issues like this one.

**Comment by manuelscurti** [comment]
I tried to generate a new token and checked for whitespaces but it doesn't work

![Image](https://github.com/user-attachments/assets/8bdfc2ca-89ed-41ce-9f11-a57c5313b04b)

however, I would expect to get a 401 or 403 for a wrong token right?

you mentioned the repo must be empty for first sync. repo is initialized but empty. is this ok?

**Comment by silvanocerza** [comment]
> however, I would expect to get a 401 or 403 for a wrong token right?

Yeah, the token is correct if you get a 404 now that I think about it. 

> you mentioned the repo must be empty for first sync. repo is initialized but empty. is this ok?

That's ok, I handle that case. I just tested again with a fresh repo just to make sure and it worked with no issues.

Is the `.obsidian/github-sync-metadata.json` file created remotely? If that's the case I would suggest deleting and trying again, at that point it should work. 

If there's no file remotely I would suggest testing the latest `1.0.7beta2`, use [BRAT](https://tfthacker.com/brat-quick-guide) to install it.

**Comment by sanzoghenzo** [comment]
Ciao Silvano, first of all many thanks for this plugin!

Unfortunately I'm hitting the same error with a freshly created private repository with only a README.md file in it.

This happens also with version `1.0.7-beta4` from BRAT.

```
{"timestamp":"2025-05-06T14:52:56.563Z","level":"INFO","message":"Starting first sync"}
{"timestamp":"2025-05-06T14:52:56.839Z","level":"ERROR","message":"Failed to get repo content","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-encoding":"gzip","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Tue, 06 May 2025 14:52:56 GMT","github-authentication-token-expiration":"2026-01-04 00:00:00 +0100","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-accepted-github-permissions":"contents=read","x-content-type-options":"nosniff","x-github-api-version-selected":"2022-11-28","x-github-media-type":"github.v3; format=json","x-github-request-id":"68E6:61692:75CEB0:78560B:681A2248","x-ratelimit-limit":"5000","x-ratelimit-remaining":"3911","x-ratelimit-reset":"1746545058","x-ratelimit-resource":"core","x-ratelimit-used":"1089","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/git/trees#get-a-tree","status":"404"},"text":"{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest/git/trees#get-a-tree\",\n  \"status\": \"404\"\n}\n"}}
{"timestamp":"2025-05-06T14:52:56.847Z","level":"INFO","message":"Remote repository is empty"}
{"timestamp":"2025-05-06T14:52:57.058Z","level":"ERROR","message":"Failed to create file","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-encoding":"gzip","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Tue, 06 May 2025 14:52:56 GMT","github-authentication-token-expiration":"2026-01-04 00:00:00 +0100","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-accepted-github-permissions":"contents=write; contents=write,workflows=write","x-content-type-options":"nosniff","x-github-api-version-selected":"2022-11-28","x-github-media-type":"github.v3; format=json","x-github-request-id":"68E6:61692:75CF76:7856EC:681A2248","x-ratelimit-limit":"5000","x-ratelimit-remaining":"3910","x-ratelimit-reset":"1746545058","x-ratelimit-resource":"core","x-ratelimit-used":"1090","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"404"},"text":"{\n  \"message\": \"Not Found\",\n  \"documentation_url\": \"https://docs.github.com/rest/repos/contents#create-or-update-file-contents\",\n  \"status\": \"404\"\n}\n"}}
```

**Comment by silvanocerza** [comment]
@manuelscurti can you check if this is still an issue with latest [1.0.7](https://github.com/silvanocerza/github-gitless-sync/releases/tag/1.0.7)?

**Comment by harrellbm** [comment]
I can confirm this is still an issue. Started with an empty vault and repo and got the 404 error so thought it was because the repo was uninitialized so init with a readme but am still getting these logs:   
```
{"timestamp":"2025-08-08T13:56:16.146Z","level":"INFO","message":"Starting first sync"}
{"timestamp":"2025-08-08T13:56:16.467Z","level":"ERROR","message":"Failed to get repo content","additional_data":{"status":404,"headers":{"referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","x-github-media-type":"github.v3; format=json","Server":"github.com","Vary":"Accept-Encoding, Accept, X-Requested-With","Strict-Transport-Security":"max-age=31536000; includeSubdomains; preload","x-github-request-id":"DFD5:1BB1F1:48A102:4AC001:68960200","x-ratelimit-limit":"5000","Content-Encoding":"gzip","x-accepted-github-permissions":"contents=read","x-github-api-version-selected":"2022-11-28","x-ratelimit-reset":"1754662956","Date":"Fri, 08 Aug 2025 13:56:16 GMT","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","github-authentication-token-expiration":"2026-02-28 00:00:00 -0800","Access-Control-Allow-Origin":"*","content-security-policy":"default-src 'none'","x-ratelimit-resource":"core","x-ratelimit-used":"24","x-xss-protection":"0","x-content-type-options":"nosniff","Content-Type":"application/json; charset=utf-8","x-ratelimit-remaining":"4976","x-frame-options":"deny"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/git/trees#get-a-tree","status":"404"},"text":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/git/trees#get-a-tree\",\"status\":\"404\"}"}}
{"timestamp":"2025-08-08T13:56:16.473Z","level":"INFO","message":"Remote repository is empty"}
{"timestamp":"2025-08-08T13:56:16.667Z","level":"ERROR","message":"Failed to create file","additional_data":{"status":404,"headers":{"x-content-type-options":"nosniff","x-frame-options":"deny","Content-Encoding":"gzip","Strict-Transport-Security":"max-age=31536000; includeSubdomains; preload","Server":"github.com","Vary":"Accept-Encoding, Accept, X-Requested-With","github-authentication-token-expiration":"2026-02-28 00:00:00 -0800","Access-Control-Allow-Origin":"*","x-xss-protection":"0","x-ratelimit-limit":"5000","x-ratelimit-resource":"core","x-ratelimit-reset":"1754662956","x-ratelimit-remaining":"4975","x-github-api-version-selected":"2022-11-28","x-ratelimit-used":"25","Content-Type":"application/json; charset=utf-8","x-accepted-github-permissions":"contents=write; contents=write,workflows=write","x-github-media-type":"github.v3; format=json","Date":"Fri, 08 Aug 2025 13:56:16 GMT","content-security-policy":"default-src 'none'","x-github-request-id":"DFD5:1BB1F1:48A1AA:4AC0BA:68960200","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#create-or-update-file-contents","status":"404"},"text":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/repos/contents#create-or-update-file-contents\",\"status\":\"404\"}"}}
```

**Comment by ydx1013** [comment]
i have this problem too

**Comment by deltaract** [comment]
I had a similar issue but I would get an error status 409, I managed to come up with a solution

When making a new private repo, add a README and then delete it. It should fix the sync issue.

**Comment by mayamcdougall** [comment]
I had this problem, of something similar, but it turned out that I just hadn't set the permissions properly for the access token.

GitHub's UI for this is a little unintuitive.  I didn't realize that after selecting the repo, I also had to set specific permissions in the box below it.  If you only set the repo and then hit confirm, GitHub just ignores it without warning you.

The screenshot in the readme *does* show this section, but it is very tightly cropped, and doesn't do a great job of actually showing where that permission gets set.

**Comment by Drakiss666** [comment]
Sorry to re-open that bug.
I certainly do something wrong, but I tried to add and delete the readme.
I've done the Permissions thing in the token.

<img width="801" height="617" alt="Image" src="https://github.com/user-attachments/assets/5ef99655-833c-4179-9d32-0ab1bf140302" />

But still having the same errors :
`{"timestamp":"2026-02-20T10:51:33.640Z","level":"INFO","message":"Starting first sync"}
{"timestamp":"2026-02-20T10:51:33.811Z","level":"ERROR","message":"Failed to get repo content","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Fri, 20 Feb 2026 10:51:33 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-github-media-type":"github.v3; format=json","x-github-request-id":"D39E:27E271:308A8C6:2C5F75C:69983CB5","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"},"text":"{\r\n  \"message\": \"Not Found\",\r\n  \"documentation_url\": \"https://docs.github.com/rest\",\r\n  \"status\": \"404\"\r\n}"}}
{"timestamp":"2026-02-20T10:51:33.813Z","level":"INFO","message":"Remote repository is empty"}
{"timestamp":"2026-02-20T10:51:33.927Z","level":"ERROR","message":"Failed to create file","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Fri, 20 Feb 2026 10:51:33 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-github-media-type":"github.v3; format=json","x-github-request-id":"D39E:27E271:308A9A2:2C5F833:69983CB5","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"},"text":"{\r\n  \"message\": \"Not Found\",\r\n  \"documentation_url\": \"https://docs.github.com/rest\",\r\n  \"status\": \"404\"\r\n}"}}
{"timestamp":"2026-02-20T10:56:38.481Z","level":"INFO","message":"Starting first sync"}
{"timestamp":"2026-02-20T10:56:38.663Z","level":"ERROR","message":"Failed to get repo content","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Fri, 20 Feb 2026 10:56:38 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-github-media-type":"github.v3; format=json","x-github-request-id":"D3D3:1510B4:312B152:2D02491:69983DE6","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"},"text":"{\r\n  \"message\": \"Not Found\",\r\n  \"documentation_url\": \"https://docs.github.com/rest\",\r\n  \"status\": \"404\"\r\n}"}}
{"timestamp":"2026-02-20T10:56:38.665Z","level":"INFO","message":"Remote repository is empty"}
{"timestamp":"2026-02-20T10:56:38.771Z","level":"ERROR","message":"Failed to create file","additional_data":{"status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","content-security-policy":"default-src 'none'","content-type":"application/json; charset=utf-8","date":"Fri, 20 Feb 2026 10:56:38 GMT","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","server":"github.com","strict-transport-security":"max-age=31536000; includeSubdomains; preload","vary":"Accept-Encoding, Accept, X-Requested-With","x-content-type-options":"nosniff","x-github-media-type":"github.v3; format=json","x-github-request-id":"D3D3:1510B4:312B235:2D02550:69983DE6","x-xss-protection":"0"},"arrayBuffer":{},"json":{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"},"text":"{\r\n  \"message\": \"Not Found\",\r\n  \"documentation_url\": \"https://docs.github.com/rest\",\r\n  \"status\": \"404\"\r\n}"}}`

Please, could you provide some help ?

**Comment by Drakiss666** [comment]
I created a another repository and token, and now it's working...
Computer science is not an exact science...

**Comment by jkubecki** [comment]
I had a similar issue and in my case, it was whitespace in the _repo name_.
